language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

before_script:
#  - curl -s http://getcomposer.org/installer | php
#  - php composer.phar install --dev --no-interaction
  - composer require satooshi/php-coveralls:1.0.* --dev
  - composer install --dev --no-interaction

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit-ci.xml.dist

after_script:
  - php vendor/bin/coveralls -v
